import type { User, Category, Paper } from "./types";
import { getPlaceholderImage } from "./utils";

export const dummyUser: User = {
	id: 1,
	fullName: "Alex Doe",
	email: "alex.doe@example.com",
	collegeName: "Stanford University",
	country: "USA",
	birthDate: "1998-07-15",
	role: "admin",
	avatarUrl: getPlaceholderImage("user-avatar-1")?.imageUrl || "",
	ssn: "000-00-0000",
	createdAt: "2024-01-01T00:00:00.000Z",
};

export const categories: Category[] = [
	{
		id: "cs",
		name: "Computer Science",
		description: "Algorithms, data structures, AI, and more.",
		imageUrl: getPlaceholderImage("category-cs")?.imageUrl || "",
		imageHint: getPlaceholderImage("category-cs")?.imageHint || "",
	},
	{
		id: "bio",
		name: "Biology",
		description: "Genetics, molecular biology, and ecology.",
		imageUrl: getPlaceholderImage("category-bio")?.imageUrl || "",
		imageHint: getPlaceholderImage("category-bio")?.imageHint || "",
	},
	{
		id: "phy",
		name: "Physics",
		description: "Quantum mechanics, relativity, and cosmology.",
		imageUrl: getPlaceholderImage("category-phy")?.imageUrl || "",
		imageHint: getPlaceholderImage("category-phy")?.imageHint || "",
	},
	{
		id: "chem",
		name: "Chemistry",
		description: "Organic, inorganic, and physical chemistry.",
		imageUrl: getPlaceholderImage("paper-thumb-1")?.imageUrl || "",
		imageHint: getPlaceholderImage("paper-thumb-1")?.imageHint || "",
	},
	{
		id: "math",
		name: "Mathematics",
		description: "Calculus, algebra, and number theory.",
		imageUrl: getPlaceholderImage("paper-thumb-2")?.imageUrl || "",
		imageHint: getPlaceholderImage("paper-thumb-2")?.imageHint || "",
	},
	{
		id: "econ",
		name: "Economics",
		description: "Macroeconomics, microeconomics, and econometrics.",
		imageUrl: getPlaceholderImage("paper-thumb-3")?.imageUrl || "",
		imageHint: getPlaceholderImage("paper-thumb-3")?.imageHint || "",
	},
];

export const papers: Paper[] = [
	{
		id: 1,
		title: "The Future of Machine Learning in Quantum Computing",
		description:
			"An exploration of how machine learning algorithms can be accelerated using quantum computing principles, with a focus on optimization problems.",
		authorId: 2,
		authorName: "Dr. Evelyn Reed",
		authorAvatar: getPlaceholderImage("user-avatar-2")?.imageUrl || "",
		pdfUrl: "/placeholder.pdf",
		categoryId: "cs",
		categoryName: "Computer Science",
		status: "approved",
		approvedBy: 1,
		createdAt: "2024-05-10T14:48:00.000Z",
		updatedAt: "2024-05-10T14:48:00.000Z",
		reactionCount: 120,
		commentCount: 45,
		saveCount: 88,
	},
	{
		id: 2,
		title: "CRISPR-Cas9 Gene Editing: A New Frontier in Biology",
		description:
			"A comprehensive review of the CRISPR-Cas9 system, its applications in genetic engineering, and the ethical considerations surrounding its use.",
		authorId: 3,
		authorName: "Dr. Ben Carter",
		authorAvatar: getPlaceholderImage("user-avatar-1")?.imageUrl || "",
		pdfUrl: "/placeholder.pdf",
		categoryId: "bio",
		categoryName: "Biology",
		status: "approved",
		approvedBy: 1,
		createdAt: "2024-05-20T09:21:00.000Z",
		updatedAt: "2024-05-20T09:21:00.000Z",
		reactionCount: 256,
		commentCount: 98,
		saveCount: 150,
	},
	{
		id: 3,
		title: "Observational Evidence for Dark Matter Halos",
		description:
			"This paper presents observational data from galactic rotation curves and gravitational lensing that support the existence of dark matter halos around galaxies.",
		authorId: 4,
		authorName: "Dr. Maria Garcia",
		authorAvatar: getPlaceholderImage("user-avatar-2")?.imageUrl || "",
		pdfUrl: "/placeholder.pdf",
		categoryId: "phy",
		categoryName: "Physics",
		status: "pending",
		createdAt: "2024-05-22T18:00:00.000Z",
		updatedAt: "2024-05-22T18:00:00.000Z",
		reactionCount: 0,
		commentCount: 0,
		saveCount: 0,
	},
	{
		id: 4,
		title: "A Novel Approach to Asymmetric Catalysis in Organic Chemistry",
		description:
			"Introducing a new chiral ligand for rhodium-catalyzed reactions, achieving unprecedented enantioselectivity in various transformations.",
		authorId: 1,
		authorName: dummyUser.fullName,
		authorAvatar: dummyUser.avatarUrl,
		pdfUrl: "/placeholder.pdf",
		categoryId: "chem",
		categoryName: "Chemistry",
		status: "rejected",
		rejectionReason:
			"Methodology section lacks sufficient detail for reproducibility.",
		createdAt: "2024-04-15T11:30:00.000Z",
		updatedAt: "2024-04-15T11:30:00.000Z",
		reactionCount: 0,
		commentCount: 0,
		saveCount: 0,
	},
	{
		id: 5,
		title: "The Riemann Hypothesis: A Modern Perspective",
		description:
			"A survey of recent progress and computational approaches towards solving the Riemann Hypothesis, one of mathematics' most famous unsolved problems.",
		authorId: 5,
		authorName: "Prof. Kenji Tanaka",
		authorAvatar: getPlaceholderImage("user-avatar-1")?.imageUrl || "",
		pdfUrl: "/placeholder.pdf",
		categoryId: "math",
		categoryName: "Mathematics",
		status: "approved",
		approvedBy: 1,
		createdAt: "2024-05-01T10:00:00.000Z",
		updatedAt: "2024-05-01T10:00:00.000Z",
		reactionCount: 301,
		commentCount: 112,
		saveCount: 205,
	},
];

export const savedPapers = [papers[1], papers[4]];
