import type { User, Category, Paper } from './types';
import { getPlaceholderImage } from './utils';

export const dummyUser: User = {
  id: 'user-1',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  college: 'Stanford University',
  country: 'USA',
  birthDate: '1998-07-15',
  role: 'admin',
  avatarUrl: getPlaceholderImage('user-avatar-1')?.imageUrl || '',
  ssn: '000-00-0000',
};

export const categories: Category[] = [
  { id: 'cs', name: 'Computer Science', description: 'Algorithms, data structures, AI, and more.', imageUrl: getPlaceholderImage('category-cs')?.imageUrl || '', imageHint: getPlaceholderImage('category-cs')?.imageHint || '' },
  { id: 'bio', name: 'Biology', description: 'Genetics, molecular biology, and ecology.', imageUrl: getPlaceholderImage('category-bio')?.imageUrl || '', imageHint: getPlaceholderImage('category-bio')?.imageHint || '' },
  { id: 'phy', name: 'Physics', description: 'Quantum mechanics, relativity, and cosmology.', imageUrl: getPlaceholderImage('category-phy')?.imageUrl || '', imageHint: getPlaceholderImage('category-phy')?.imageHint || '' },
  { id: 'chem', name: 'Chemistry', description: 'Organic, inorganic, and physical chemistry.', imageUrl: getPlaceholderImage('paper-thumb-1')?.imageUrl || '', imageHint: getPlaceholderImage('paper-thumb-1')?.imageHint || '' },
  { id: 'math', name: 'Mathematics', description: 'Calculus, algebra, and number theory.', imageUrl: getPlaceholderImage('paper-thumb-2')?.imageUrl || '', imageHint: getPlaceholderImage('paper-thumb-2')?.imageHint || '' },
  { id: 'econ', name: 'Economics', description: 'Macroeconomics, microeconomics, and econometrics.', imageUrl: getPlaceholderImage('paper-thumb-3')?.imageUrl || '', imageHint: getPlaceholderImage('paper-thumb-3')?.imageHint || '' },
];

export const papers: Paper[] = [
  {
    id: 'paper-1',
    name: 'The Future of Machine Learning in Quantum Computing',
    description: 'An exploration of how machine learning algorithms can be accelerated using quantum computing principles, with a focus on optimization problems.',
    authorId: 'user-2',
    authorName: 'Dr. Evelyn Reed',
    authorAvatar: getPlaceholderImage('user-avatar-2')?.imageUrl || '',
    pdfUrl: '/placeholder.pdf',
    categoryId: 'cs',
    status: 'approved',
    approvedBy: 'admin-1',
    createdAt: '2024-05-10T14:48:00.000Z',
    summary: 'This paper reviews the synergistic potential of combining machine learning with quantum computing. It highlights several quantum algorithms that offer exponential speedups for classical machine learning tasks and discusses the challenges in building practical quantum machine learning systems.',
    interactions: { reactions: 120, comments: 45, saves: 88, shares: 32 },
  },
  {
    id: 'paper-2',
    name: 'CRISPR-Cas9 Gene Editing: A New Frontier in Biology',
    description: 'A comprehensive review of the CRISPR-Cas9 system, its applications in genetic engineering, and the ethical considerations surrounding its use.',
    authorId: 'user-3',
    authorName: 'Dr. Ben Carter',
    authorAvatar: getPlaceholderImage('user-avatar-1')?.imageUrl || '',
    pdfUrl: '/placeholder.pdf',
    categoryId: 'bio',
    status: 'approved',
    approvedBy: 'admin-1',
    createdAt: '2024-05-20T09:21:00.000Z',
    summary: 'The paper details the mechanisms of the CRISPR-Cas9 gene-editing tool. It covers its transformative impact on biological research, potential therapeutic uses, and the ongoing ethical debates about germline modification.',
    interactions: { reactions: 256, comments: 98, saves: 150, shares: 55 },
  },
  {
    id: 'paper-3',
    name: 'Observational Evidence for Dark Matter Halos',
    description: 'This paper presents observational data from galactic rotation curves and gravitational lensing that support the existence of dark matter halos around galaxies.',
    authorId: 'user-4',
    authorName: 'Dr. Maria Garcia',
    authorAvatar: getPlaceholderImage('user-avatar-2')?.imageUrl || '',
    pdfUrl: '/placeholder.pdf',
    categoryId: 'phy',
    status: 'pending',
    createdAt: '2024-05-22T18:00:00.000Z',
    summary: 'By analyzing the rotational velocities of stars in distant galaxies, this study provides strong evidence that the visible matter alone cannot account for the gravitational forces observed. The findings support the theory of vast, invisible dark matter halos.',
    interactions: { reactions: 0, comments: 0, saves: 0, shares: 0 },
  },
  {
    id: 'paper-4',
    name: 'A Novel Approach to Asymmetric Catalysis in Organic Chemistry',
    description: 'Introducing a new chiral ligand for rhodium-catalyzed reactions, achieving unprecedented enantioselectivity in various transformations.',
    authorId: 'user-1',
    authorName: dummyUser.name,
    authorAvatar: dummyUser.avatarUrl,
    pdfUrl: '/placeholder.pdf',
    categoryId: 'chem',
    status: 'rejected',
    rejectionReason: 'Methodology section lacks sufficient detail for reproducibility.',
    createdAt: '2024-04-15T11:30:00.000Z',
    summary: 'The research introduces a novel phosphine-based ligand that demonstrates high efficiency and selectivity in asymmetric hydrogenation. The study suggests broad applicability for pharmaceutical synthesis.',
    interactions: { reactions: 0, comments: 0, saves: 0, shares: 0 },
  },
  {
    id: 'paper-5',
    name: 'The Riemann Hypothesis: A Modern Perspective',
    description: 'A survey of recent progress and computational approaches towards solving the Riemann Hypothesis, one of mathematics\' most famous unsolved problems.',
    authorId: 'user-5',
    authorName: 'Prof. Kenji Tanaka',
    authorAvatar: getPlaceholderImage('user-avatar-1')?.imageUrl || '',
    pdfUrl: '/placeholder.pdf',
    categoryId: 'math',
    status: 'approved',
    approvedBy: 'admin-1',
    createdAt: '2024-05-01T10:00:00.000Z',
    summary: 'This survey paper consolidates recent theoretical advancements and computational efforts related to the Riemann Hypothesis. It explains the significance of the hypothesis and details the most promising current avenues of research.',
    interactions: { reactions: 301, comments: 112, saves: 205, shares: 80 },
  }
];

export const savedPapers = [papers[1], papers[4]];
